# Generated by Django 3.1.4 on 2020-12-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0002_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='posted_at',
        ),
    ]
