# Generated by Django 3.1.4 on 2020-12-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0006_auto_20201224_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click above to read more..', max_length=255),
        ),
    ]
